name: My first workflow     // name of workflow 

on: push   // event

jobs:         // set of jobs
  say-hello:   // job 1
    runs-on: ubuntu-lates

    steps:      // steps to run job 1
      - name: Print message
        run: echo "Hello , GitHub Actions!"
      - name: print my name
        run: echo "Tarun , GitHub Actions!"